plugins { id 'com.android.application' }
android {
    namespace 'com.example.doorstepdelivery'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.doorstepdelivery"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes { 
        release { 
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        } 
    }
    compileOptions {
        sourceCompatibility 17
        targetCompatibility 17
    }
}
dependencies {}
